In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import Data

## Armax

In [ ]:
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\ARMAX_250.csv', sep="\t")   # 250 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\ARMAX_500.csv', sep="\t")   # 500 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\ARMAX_750.csv', sep="\t")   # 750 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\ARMAX_1000.csv', sep="\t")  # 1000 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\ARMAX_1250.csv', sep="\t")  # 1250 Nm

## Scania

In [110]:
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\Scania_250.csv', sep="\t")   # 250 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\Scania_500.csv', sep="\t")   # 500 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\Scania_750.csv', sep="\t")   # 750 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\Scania_1000.csv', sep="\t")  # 1000 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Torque\Scania_1250.csv', sep="\t")  # 1250 Nm

# Extract Data
- **OTSV1** : 3 way valve
- **TV12**  : Inlet Temp to Gearbox
- **TV11**  : Outlet Temp from Gearbox
- **OTGT1** : Inlet Temp to Heat Exchanger (HE)
- **OTGT2** : Assume same as OTGT3
- **OTGT3** : Temp from HE to Cooling HE
- **OTGT4** : Cooling Temp into 3 way valve
- **QV11**  : Flow Rate (Liter/Min)
- **OTGL6** : Heating valve Temp
- **KVSV1** : Cooling valve Temp
- **KVGT1** : Cooling water Temp
- **KVGT2** : Temp out from cooling HE

In [111]:
clean_data = data[['OTSV1', 'TV12', 'TV11', 'OTGT1', 'OTGT2', 'OTGT3', 'OTGT4', 'QV11', 'OTGL6', 'KVSV1', 'KVGT1', 'KVGT2']]
clean_data

,OTSV1,TV12,TV11,OTGT1,OTGT2,OTGT3,OTGT4,QV11,OTGL6,KVSV1,KVGT1,KVGT2
0,"21,758","49,76","53,48","50,05","49,9","49,75","45,32","10,093000411987305",0,8,"48,74","27,51"
1,"21,758","49,76","53,48","50,05","49,9","49,75","45,32","10,093000411987305",0,8,"48,74","27,51"
2,"21,758","49,76","53,48","50,05","49,9","49,75","45,32","10,093000411987305",0,8,"48,74","27,51"
3,"21,758","49,76","53,48","50,05","49,9","49,75","45,32","10,093000411987305",0,8,"48,74","27,51"
4,"21,758","49,76","53,48","50,05","49,9","49,75","45,32","10,093000411987305",0,8,"48,74","27,51"
...,...,...,...,...,...,...,...,...,...,...,...,...
703422,"23,629","49,67","54,51","49,87","49,73","49,62","45,03","10,071000099182129",0,"7,2","48,65",27
703423,"23,629","49,67","54,51","49,87","49,73","49,62","45,03","10,071000099182129",0,"7,2","48,65",27
703424,"23,629","49,67","54,51","49,87","49,73","49,62","45,03","10,071000099182129",0,"7,2","48,65",27
703425,"23,629","49,67","54,51","49,87","49,73","49,62","45,03","10,071000099182129",0,"7,2","48,66",27
703426,"23,629","49,67","54,51","49,87","49,73","49,62","45,03","10,071000099182129",0,"7,2","48,66",27

## Armax

In [ ]:
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\ARMAX_250.csv', index=False, encoding='utf-8')    # 250 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\ARMAX_500.csv', index=False, encoding='utf-8')    # 500 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\ARMAX_750.csv', index=False, encoding='utf-8')    # 750 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\ARMAX_1000.csv', index=False, encoding='utf-8')    # 1000 Nm
clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\ARMAX_1250.csv', index=False, encoding='utf-8')    # 1250 Nm

## Scania

In [113]:
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\Scania_250.csv', index=False, encoding='utf-8')    # 250 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\Scania_500.csv', index=False, encoding='utf-8')    # 500 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\Scania_750.csv', index=False, encoding='utf-8')    # 750 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\Scania_1000.csv', index=False, encoding='utf-8')    # 1000 Nm
clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Torque\Scania_1250.csv', index=False, encoding='utf-8')    # 1250 Nm