In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import Data

## Armax

In [ ]:
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_350.csv', sep="\t")   # 350 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_700.csv', sep="\t")   # 700 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_1050.csv', sep="\t")  # 1050 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_1400.csv', sep="\t")  # 1400 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_2100.csv', sep="\t")  # 2100 Nm - No OTSV1_FB_LREAL
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_2450.csv', sep="\t")  # 2450 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_2800.csv', sep="\t")  # 2800 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_3150.csv', sep="\t")  # 3150 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\ARMAX\ARMAX_3500.csv', sep="\t")  # 3500 Nm

## Scania

In [77]:
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_350.csv', sep="\t")   # 350 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_700.csv', sep="\t")   # 700 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_1050.csv', sep="\t")  # 1050 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_1400.csv', sep="\t")  # 1400 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_2100.csv', sep="\t")  # 2100 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_2450.csv', sep="\t")  # 2450 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_2800.csv', sep="\t")  # 2800 Nm
#data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_3150.csv', sep="\t")  # 3150 Nm
data = pd.read_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Flow\Scania\Scania_3500.csv', sep="\t")  # 3500 Nm

# Extract Data
- **OTSV1** : 3 way valve
- **TV12**  : Inlet Temp to Gearbox
- **TV11**  : Outlet Temp from Gearbox
- **OTGT1** : Inlet Temp to Heat Exchanger (HE)
- **OTGT2** : Assume same as OTGT3
- **OTGT3** : Temp from HE to Cooling HE
- **OTGT4** : Cooling Temp into 3 way valve
- **QV11**  : Flow Rate (Liter/Min)
- **OTGL6** : Heating valve Temp
- **KVSV1** : Cooling valve Temp
- **KVGT1** : Cooling water Temp
- **KVGT2** : Temp out from cooling HE
- **OTGP1** : Pressure into HE

In [78]:
clean_data = data[['OTSV1', 'TV12', 'TV11', 'OTGT1', 'OTGT2', 'OTGT3', 'OTGT4', 'OTGT6', 'QV11', 'OTSV1_FB_LREAL', 'KVSV1', 'KVGT1', 'KVGT2', 'OTGP1']]
#clean_data = data[['OTSV1', 'TV12', 'TV11', 'OTGT1', 'OTGT2', 'OTGT3', 'OTGT4', 'QV11', 'KVSV1', 'KVGT1', 'KVGT2']]
clean_data

,OTSV1,TV12,TV11,OTGT1,OTGT2,OTGT3,OTGT4,OTGT6,QV11,OTSV1_FB_LREAL,KVSV1,KVGT1,KVGT2,OTGP1
0,13.120,48.36,52.74,48.01,48.32,48.24,45.71,92.83,10.055,11,5.9,48.06,27.23,2.287756
1,13.120,48.36,52.74,48.01,48.32,48.24,45.71,92.83,10.055,11,5.9,48.06,27.23,2.287756
2,13.120,48.36,52.74,48.01,48.32,48.24,45.71,92.83,10.055,11,5.9,48.06,27.23,2.287756
3,13.120,48.36,52.74,48.01,48.32,48.24,45.71,92.83,10.055,11,5.9,48.06,27.23,2.287756
4,13.120,48.36,52.74,48.01,48.32,48.24,45.71,92.83,10.055,11,5.9,48.06,27.23,2.287756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428864,12.745,48.20,52.43,48.43,48.16,48.08,46.17,92.56,10.091,11,5.5,47.98,27.44,2.414337
428865,12.745,48.20,52.43,48.43,48.16,48.07,46.17,92.56,10.091,11,5.5,47.95,27.44,2.285115
428866,12.745,48.20,52.43,48.43,48.16,48.07,46.17,92.56,10.091,11,5.5,47.95,27.44,2.285115
428867,12.745,48.20,52.43,48.43,48.16,48.07,46.17,92.56,10.091,11,5.5,47.95,27.44,2.285115
428868,12.745,48.20,52.43,48.43,48.16,48.07,46.17,92.56,10.091,11,5.5,47.95,27.44,2.285115

# Save Data to CSV

## Armax

In [ ]:
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_350.csv', index=False, encoding='utf-8')     # 350 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_700.csv', index=False, encoding='utf-8')     # 700 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_1050.csv', index=False, encoding='utf-8')    # 1050 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_1400.csv', index=False, encoding='utf-8')    # 1400 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_2100.csv', index=False, encoding='utf-8')    # 2100 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_2450.csv', index=False, encoding='utf-8')    # 2450 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_2800.csv', index=False, encoding='utf-8')    # 2800 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_3150.csv', index=False, encoding='utf-8')    # 3150 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\ARMAX\ARMAX_3500.csv', index=False, encoding='utf-8')    # 3500 Nm

## Scania

In [79]:
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_350.csv', index=False, encoding='utf-8')     # 350 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_700.csv', index=False, encoding='utf-8')     # 700 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_1050.csv', index=False, encoding='utf-8')    # 1050 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_1400.csv', index=False, encoding='utf-8')    # 1400 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_2100.csv', index=False, encoding='utf-8')    # 2100 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_2450.csv', index=False, encoding='utf-8')    # 2450 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_2800.csv', index=False, encoding='utf-8')    # 2800 Nm
#clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_3150.csv', index=False, encoding='utf-8')    # 3150 Nm
clean_data.to_csv(r'C:\Users\jerem\Documents\Python Scripts\Scania\RQ2_Data\Clean_Data\Flow\Scania\Scania_3500.csv', index=False, encoding='utf-8')    # 3500 Nm